### ISSUE TITLE
Theme the site and prettify the site-wide components

### ISSUE THREAD

**Issue by AeroStun** [CoffeeMine/CoffeeMine#5]
Branch: material-design
Goals:
- [x] Modify Vaadin Material Design to suit our needs.
- [x] Prettify the navbar.
- [x] Think about usability. (make mockups)

**Comment by RuthgerD** [comment]
Time spent:
* 4 hours, 2019-11-19

**Comment by RuthgerD** [comment]
For home page
Mockup 1# (old colors)
![image](https://user-images.githubusercontent.com/57626200/69495600-0c8cf080-0ec9-11ea-86c4-f17dd48c10ff.png)

Mockup 2#
![image](https://user-images.githubusercontent.com/57626200/69495595-fed76b00-0ec8-11ea-9a29-6409d2eee4e5.png)
