### ISSUE TITLE
Oveview

### ISSUE THREAD

**Issue by crz11111** [CoffeeMine/CoffeeMine#55]
Needs fix:
- [x] [details] button is not implemented for tasks view
- [x] missing recent changes display

Would be nice:
- [ ] Tasks view scrolling with scroll wheel is not smooth (stops directly)

**Comment by RuthgerD** [comment]
* 1 hour

**Comment by RuthgerD** [comment]
foundation done, Tasks and Sprints are now displayed properly. In the future we might want to add TrackItems as well.
